name: Packaging

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  PROJECT: buvar_aiohttp
  # renovate: datasource=github-tags depName=uv lookupName=astral-sh/uv
  UV_VERSION: 0.7.13

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: ${{ env.UV_VERSION }}

      - run: uv sync --dev --frozen
      - run: uv run pytest --cov ${{ env.PROJECT }}

      - name: Build source distribution
        run: uv build --sdist

      - name: archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT }}-sdist
          retention-days: 1
          path: |
            ./dist/${{ env.PROJECT }}-*.tar.gz
            ./dist/${{ env.PROJECT }}-*.whl

  publish:
    needs:
      - package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PROJECT }}  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.PROJECT }}-sdist
          path: dist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

